[package]
name = "m-mazing"
version = "0.1.0"
edition = "2021"
authors = ["Travis Finkenauer <tmfinken@gmail.com>"]
license = "MIT OR Apache-2.0"
categories = ["games"]
description = "Game based on Magic Maze"


[dependencies]
arrayvec = "0.7"
env_logger = "0.9"
log = "0.4"
thiserror = "1"
