[package]
name = "m-mazing-tile-util"
version = "0.1.0"
edition = "2021"

[dependencies]
m-mazing-core = { path = "../m-mazing-core" }

anyhow = "1.0"
clap = { version = "3", features = ["derive"] }
notify = "5.0"
